server.port=8081
spring.application.name=FestivalOrganizer
spring.mvc.hiddenmethod.filter.enabled=true

spring.datasource.url=jdbc:postgresql://localhost:5432/festivalorganizer_db
spring.datasource.username=postgres
spring.datasource.password=Jgames22$
spring.jpa.hibernate.ddl-auto=update